name: foxlator-lib pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment:
      name: foxlator-lib
      url: https://pypi.org/p/foxlator-lib
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: ./bin/install-deps.sh
      - name: "Build wheel package"
        run: ./bin/build-package.sh
      - name: "Perform a smoke test"
        run: ./bin/smoke-test.sh
      - name: "Bump build number"
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --global user.email "skyfox.comp@gmail.com"
          git config --global user.name 'Skyfox.Builder'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          ./bin/bump-version.sh --build
      - name: Release to PyPI
        if: github.ref == 'refs/heads/dev'
        run: |
          python3.10 -m twine upload  dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }}
